[package]
name = "codegen-sdk-analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
salsa = "0.16.1"
codegen-sdk-ast = { path = "../codegen-sdk-ast" }
[dev-dependencies]
test-log = { workspace = true }
